<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    public function run()
    {
        $cities = [
       
    'Aïn Harrouda',
    'Ben Yakhlef',
    'Bouskoura',
    'Casablanca',
    'Médiouna',
    'Mohammadia',
    'Tit Mellil',
    'Ben Yakhlef',
    'Bejaâd',
    'Ben Ahmed',
    'Benslimane',
    'Berrechid',
    'Boujniba',
    'Boulanouare',
    'Bouznika',
    'Deroua',
    'El Borouj',
    'El Gara',
    'Guisser',
    'Hattane',
    'Khouribga',
    'Loulad',
    'Oued Zem',
    'Oulad Abbou',
    'Oulad HRiz Sahel',
    'Oulad Mrah',
    'Oulad Saïd',
    'Oulad Sidi Ben Daoud',
    'Ras El Aïn',
    'Settat',
    'Sidi Rahhal Chataï',
    'Soualem',
    'Azemmour',
    'Bir Jdid',
    'Bouguedra',
    'Echemmaia',
    'El Jadida',
    'Hrara',
    'Ighoud',
    'Jamâat Shaim',
    'Jorf Lasfar',
    'Khemis Zemamra',
    'Laaounate',
    'Moulay Abdallah',
    'Oualidia',
    'Oulad Amrane',
    'Oulad Frej',
    'Oulad Ghadbane',
    'Safi',
    'Sebt El Maârif',
    'Sebt Gzoula',
    'Sidi Ahmed',
    'Sidi Ali Ban Hamdouche',
    'Sidi Bennour',
    'Sidi Bouzid',
    'Sidi Smaïl',
    'Youssoufia',
    'Fès',
    'Aïn Cheggag',
    'Bhalil',
    'Boulemane',
    'El Menzel',
    'Guigou',
    'Imouzzer Kandar',
    'Imouzzer Marmoucha',
    'Missour',
    'Moulay Yaâcoub',
    'Ouled Tayeb',
    'Outat El Haj',
    'Ribate El Kheir',
    'Séfrou',
    'Skhinate',
    'Tafajight',
    'Arbaoua',
    'Aïn Dorij',
    'Dar Gueddari',
    'Had Kourt',
    'Jorf El Melha',
    'Kénitra',
    'Khenichet',
    'Lalla Mimouna',
    'Mechra Bel Ksiri',
    'Mehdia',
    'Moulay Bousselham',
    'Sidi Allal Tazi',
    'Sidi Kacem',
    'Sidi Slimane',
    'Sidi Taibi',
    'Sidi Yahya El Gharb',
    'Souk El Arbaa',
    'Akka',
    'Assa',
    'Bouizakarne',
    'El Ouatia',
    'Es-Semara',
    'Fam El Hisn',
    'Foum Zguid',
    'Guelmim',
    'Taghjijt',
    'Tan-Tan',
    'Tata',
    'Zag',
    'Marrakech',
    'Ait Daoud',
    'Amizmiz',
    'Assahrij',
    'Aït Ourir',
    'Ben Guerir',
    'Chichaoua',
    'El Hanchane',
    'El Kelaâ des Sraghna',
    'Essaouira',
    'Fraïta',
    'Ghmate',
    'Ighounane',
    'Imintanoute',
    'Kattara',
    'Lalla Takerkoust',
    'Loudaya',
    'Lâattaouia',
    'Moulay Brahim',
    'Mzouda',
    'Ounagha',
    'Sid LMokhtar',
    'Sid Zouin',
    'Sidi Abdallah Ghiat',
    'Sidi Bou Othmane',
    'Sidi Rahhal',
    'Skhour Rehamna',
    'Smimou',
    'Tafetachte',
    'Tahannaout',
    'Talmest',
    'Tamallalt',
    'Tamanar',
    'Tamansourt',
    'Tameslouht',
    'Tanalt',
    'Zeubelemok',
    'Meknès',
    'Khénifra',
    'Agourai',
    'Ain Taoujdate',
    'MyAliCherif',
    'Rissani',
    'Amalou Ighriben',
    'Aoufous',
    'Arfoud',
    'Azrou',
    'Aïn Jemaa',
    'Aïn Karma',
    'Aïn Leuh',
    'Aït Boubidmane',
    'Aït Ishaq',
    'Boudnib',
    'Boufakr',
    'Boumia',
    'Erfoud',
    'Errachidia',
    'Erramlia',
    'Goulmima',
    'Gourrama',
    'Guercif',
    'Ifrane',
    'Ihddaden',
    'Imilchil',
    'Inzegane',
    'Irherm',
    'Kehf Nsour',
    'Kelaat-MGouna',
    'Kerrouchen',
    'Khenifra',
    'Mrirt',
    'Meknès',
    'Midelt',
    'Moulay Ali Cherif',
    'Moulay Bouazza',
    'Moulay Driss Zerhoun',
    'Moussaoua',
    'N Zalat Bni Amar',
    'Ouaoumana',
    'Oued Ifrane',
    'Outat',
    'Ouzoud',
    'Rissani',
    'Sabaa Aiyoun',
    'Sebt Jahjouh',
    'Selouane',
    'Sidi Addi',
    'Sidi Aiissa Messaouda',
    'Sidi Boubker',
    'Sidi Harazem',
    'Sidi Slimane Echcharaa',
    'Tafoghalt',
    'Tichoute',
    'Tighassaline',
    'Tighza',
    'Timahdite',
    'Tinejdad',
    'Tizguite',
    'Tizi n\'Isly',
    'Toulal',
    'Zaouia d\'Ifrane',
    'Zaouia Sidi Kacem',
    'Zaïda',
    'Zerhoun',
    'Zerkten',
    'Zirara',
    'Taza',
    'Al Hoceima',
    'Ait Kamra',
    'Ajdir',
    'Bni Bouayach',
    'Bni Hadifa',
    'Bni Seddat',
    'Issaguen',
    'Talambote',
    'Aknoul',
    'Al Aaroui',
    'Dar Bni Karrich',
    'Guiguis',
    'Imrabten',
    'Kariat Arekmane',
    'Tissa',
    'Tizi Ouasli',
    'Taounate',
    'Aïn Dorbane',
    'Aïn Jemaa',
    'Aïn Mediouna',
    'Aïn Taoujdate',
    'Bab Berred',
    'Bab Taza',
    'Bouadel',
    'Dar El Kebdani',
    'Debdou',
    'Douar Kannine',
    'Driouch',
    'El Aïoun Sidi Mellouk',
    'El Fedjoudj',
    'Guercif',
    'Jbel Lahbib',
    'Jerada',
    'Karia',
    'Kariat Arkmane',
    'Kassita',
    'Ketama',
    'Khénifra',
    'Laâtamna',
    'Larache',
    'M\'rirt',
    'Meknès',
    'Midar',
    'Nador',
    'Oued Heimer',
    'Oujda',
    'Oulad Ali Youssef',
    'Oulad Mkoudou',
    'Oulad Zbair',
    'Ras El Ma',
    'Saïdia',
    'Sebaa Rouadi',
    'Sefrou',
    'Selouane',
    'Tafersit',
    'Tafrant',
    'Tahla',
    'Tainaste',
    'Tamassint',
    'Taourirt',
    'Targuist',
    'Taza',
    'Temsamane',
    'Tendrara',
    'Tétouan',
    'Tissa',
    'Tizi Gheniff',
    'Tizi Ouasli',
    'Zaïo',
    'Zeghanghane',
    'Zerarda',
    'Zoumi',
    'Tétouan',
    'Fnideq',
    'M\'Diq',
    'Restinga',
    'Tanger',
    'Ain Tindamine',

        ];

        foreach ($cities as $city) {
            DB::table('cities')->insert([
                'name' => $city,
            ]);
        }
    }
}




